version: "3.3"
services:
  lexica-virtual-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      PORT: $PORT
      MONGO_URL: $MONGO_URL
      REDIS_URL: $REDIS_URL
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      NLP_URL: $NLP_URL
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      AWS_S3_API_VERSION: $AWS_S3_API_VERSION
      AWS_S3_BUCKET: $AWS_S3_BUCKET
      AWS_TRANSCODER_API_VERSION: AWS_TRANSCODER_API_VERSION
      AWS_TRANSCODER_DELAY: AWS_TRANSCODER_DELAY
      AWS_TRANSCODER_MAX_ATTEMPTS: AWS_TRANSCODER_MAX_ATTEMPTS
      AWS_TRANSCODER_AUDIO_PIPELINE_ID: AWS_TRANSCODER_AUDIO_PIPELINE_ID
      AWS_TRANSCODER_AUDIO_PRESET_ID: AWS_TRANSCODER_AUDIO_PRESET_ID
      AWS_TRANSCODER_AUDIO_SUFFIX: AWS_TRANSCODER_AUDIO_SUFFIX
      AWS_TRANSCODER_AUDIO_CONTENT_TYPE: AWS_TRANSCODER_AUDIO_CONTENT_TYPE
      AWS_TRANSCODER_VIDEO_PIPELINE_ID: AWS_TRANSCODER_VIDEO_PIPELINE_ID
      AWS_TRANSCODER_VIDEO_PRESET_ID: AWS_TRANSCODER_VIDEO_PRESET_ID
      AWS_TRANSCODER_VIDEO_SUFFIX: AWS_TRANSCODER_VIDEO_SUFFIX
      AWS_TRANSCODER_VIDEO_CONTENT_TYPE: AWS_TRANSCODER_VIDEO_CONTENT_TYPE
  mongodb:
    image: "mongo:3.6"
    ports:
      - 0:27017
  redis:
    image: "redis:alpine"